In [64]:
import pandas as pd

In [65]:
df = pd.read_csv('../preprocessing/clean_text.csv')
df

,full_text,case_folding,tokens,normalized,stopword_removal,stemming
0,Chale Your man start dey do Crypto Football ay...,chale your man start dey do crypto football ay...,"['chale', 'your', 'man', 'start', 'dey', 'do',...","['chale', 'your', 'man', 'start', 'dey', 'di',...","['chale', 'man', 'start', 'dey', 'crypto', 'fo...","['chale', 'man', 'start', 'dey', 'crypto', 'fo..."
1,Bitcoin Orange OGsatoshis,bitcoin orange ogsatoshis,"['bitcoin', 'orange', 'ogsatoshis']","['bitcoin', 'orange', 'ogsatoshis']","['bitcoin', 'orange', 'ogsatoshis']","['bitcoin', 'orange', 'ogsatoshis']"
2,WahyuS Problem terbesar yg diselesaikan web ad...,wahyus problem terbesar yg diselesaikan web ad...,"['wahyus', 'problem', 'terbesar', 'yg', 'disel...","['wahyus', 'problem', 'terbesar', 'yang', 'dis...","['wahyus', 'problem', 'terbesar', 'diselesaika...","['wahyus', 'problem', 'besar', 'selesai', 'web..."
3,Buat ngejelasin ke boomer yang bilang Underwea...,buat ngejelasin ke boomer yang bilang underwea...,"['buat', 'ngejelasin', 'ke', 'boomer', 'yang',...","['buat', 'menjelaskan', 'ke', 'boomer', 'yang'...","['boomer', 'bilang', 'underwear', 'eh', 'under...","['boomer', 'bilang', 'underwear', 'eh', 'under..."
4,Ek aisi wife to main bhi deserve karta hu yaar,ek aisi wife to main bhi deserve karta hu yaar,"['ek', 'aisi', 'wife', 'to', 'main', 'bhi', 'd...","['ek', 'aisi', 'wife', 'tapi', 'main', 'bhi', ...","['ek', 'aisi', 'wife', 'main', 'bhi', 'deserve...","['ek', 'aisi', 'wife', 'main', 'bhi', 'deserve..."
...,...,...,...,...,...,...
1231,Siapa yang akan Menjadi Raja Mata Uang Crypto ...,siapa yang akan menjadi raja mata uang crypto ...,"['siapa', 'yang', 'akan', 'menjadi', 'raja', '...","['siapa', 'yang', 'akan', 'menjadi', 'raja', '...","['raja', 'mata', 'uang', 'crypto', 'bitcoin', ...","['raja', 'mata', 'uang', 'crypto', 'bitcoin', ..."
1232,Ktk Kampuni zenye Market Cap kubwa Duniani or ...,ktk kampuni zenye market cap kubwa duniani or ...,"['ktk', 'kampuni', 'zenye', 'market', 'cap', '...","['ktk', 'kampuni', 'zenye', 'market', 'cap', '...","['ktk', 'kampuni', 'zenye', 'market', 'cap', '...","['ktk', 'kampuni', 'zenye', 'market', 'cap', '..."
1233,meinmokhtar Hang keje tak Penuhkan ASB k sbb d...,meinmokhtar hang keje tak penuhkan asb k sbb d...,"['meinmokhtar', 'hang', 'keje', 'tak', 'penuhk...","['meinmokhtar', 'hang', 'keje', 'tak', 'penuhk...","['meinmokhtar', 'hang', 'keje', 'penuhkan', 'a...","['meinmokhtar', 'hang', 'keje', 'penuh', 'asb'..."
1234,Join disini Gabung belajar santuy bareng Crypt...,join disini gabung belajar santuy bareng crypt...,"['join', 'disini', 'gabung', 'belajar', 'santu...","['join', 'disini', 'gabung', 'belajar', 'santu...","['join', 'gabung', 'belajar', 'santuy', 'baren...","['join', 'gabung', 'ajar', 'santuy', 'bareng',..."
1235,Selamat pagi di pagi hari ini CVX mengalami ke...,selamat pagi di pagi hari ini cvx mengalami ke...,"['selamat', 'pagi', 'di', 'pagi', 'hari', 'ini...","['selamat', 'pagi', 'di', 'pagi', 'hari', 'ini...","['selamat', 'pagi', 'pagi', 'cvx', 'mengalami'...","['selamat', 'pagi', 'pagi', 'cvx', 'alami', 'n..."

In [66]:
df.drop(columns=['full_text', 'case_folding', 'tokens', 'normalized', 'stopword_removal'], inplace=True)
df

                                               stemming
0     ['chale', 'man', 'start', 'dey', 'crypto', 'fo...
1                   ['bitcoin', 'orange', 'ogsatoshis']
2     ['wahyus', 'problem', 'besar', 'selesai', 'web...
3     ['boomer', 'bilang', 'underwear', 'eh', 'under...
4     ['ek', 'aisi', 'wife', 'main', 'bhi', 'deserve...
...                                                 ...
1231  ['raja', 'mata', 'uang', 'crypto', 'bitcoin', ...
1232  ['ktk', 'kampuni', 'zenye', 'market', 'cap', '...
1233  ['meinmokhtar', 'hang', 'keje', 'penuh', 'asb'...
1234  ['join', 'gabung', 'ajar', 'santuy', 'bareng',...
1235  ['selamat', 'pagi', 'pagi', 'cvx', 'alami', 'n...

[1236 rows x 1 columns]

In [69]:
#Labeling

#set lexicon
pos_inset = pd.read_csv('../../Inset/positive.tsv', sep='\t', header=None, names=['word', 'weight'])
neg_inset = pd.read_csv('../../Inset/negative.tsv', sep='\t', header=None, names=['word', 'weight'])
sentis = set(pd.read_csv('../../sentistrength_id/sentiwordsid.csv', header=None)[0])
import pandas as pd
import ast


# Pastikan kolom 'stemming' diubah dari string ke list
df['stemming'] = df['stemming'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

# Baca leksikon Inset
# Format tsv: kata\tbobot (atau hanya kata saja)
# Kita akan asumsikan format: kata\tbobot

# Buat kamus leksikon
positive_lexicon = set(pos_inset['word'].str.lower().tolist())
negative_lexicon = set(neg_inset['word'].str.lower().tolist())

print(f"Jumlah kata positif: {len(positive_lexicon)}")
print(f"Jumlah kata negatif: {len(negative_lexicon)}")

def label_sentiment(tokens):
    """
    Label sentimen berdasarkan kemunculan kata dalam leksikon Inset.
    Hanya dua kelas: positif dan negatif.
    Jika tidak ada kata yang cocok, beri label 'netral'.
    """
    if not isinstance(tokens, list):
        return 'netral'
    
    # Hitung kemunculan kata positif dan negatif
    pos_count = sum(1 for word in tokens if word.lower() in positive_lexicon)
    neg_count = sum(1 for word in tokens if word.lower() in negative_lexicon)
    score = pos_count - neg_count
    # Hanya dua kelas: positif dan negatif
    # Jika ada kata positif dan tidak ada kata negatif → positif
    # Jika ada kata negatif dan tidak ada kata positif → negatif
    # Jika ada keduanya atau tidak ada sama sekali → netral (tapi kita beri label negatif sebagai default)
    
    if pos_count > 0 and neg_count == 0:
        label = 'positif'
    elif neg_count > 0 and pos_count == 0:
        label = 'negatif'
    elif score > 0:
        label = 'positif'
    else:
        # Jika sama atau tidak ada yang cocok, default ke 'negatif'
        # Atau bisa diubah ke 'netral' jika ingin tiga kelas
        label = 'negatif'
    
    return score, label

# Terapkan pelabelan
df[['score','sentiment']] = df['stemming'].apply(lambda x: pd.Series(label_sentiment(x)))

# Tampilkan distribusi
sentiment_dist = df['sentiment'].value_counts()
print("\nDistribusi Sentimen:")
print(sentiment_dist)

# Tampilkan beberapa contoh
print("\nContoh hasil pelabelan:")
for i, row in df.head(10).iterrows():
    print(f"Stemming: {row['stemming'][:10]}...")
    print(f"Sentimen: {row['sentiment']}")
    print("-" * 80)

#df['sentiment'] = df['stemming'].apply(lambda x: pd.Series(label_sentiment_weighted(x)))
#df[['sentis_score','label_sentis']] = df['stemming'].apply(lambda x: pd.Series(labeling_sentis(x)))

df

Jumlah kata positif: 3608
Jumlah kata negatif: 6607

Distribusi Sentimen:
sentiment
negatif    810
positif    426
Name: count, dtype: int64

Contoh hasil pelabelan:
Stemming: ['chale', 'man', 'start', 'dey', 'crypto', 'football', 'ay', 'kak', 'aa', 'bitcoin']...
Sentimen: negatif
--------------------------------------------------------------------------------
Stemming: ['bitcoin', 'orange', 'ogsatoshis']...
Sentimen: negatif
--------------------------------------------------------------------------------
Stemming: ['wahyus', 'problem', 'besar', 'selesai', 'web', 'risiko', 'orang', 'orang', 'problem', 'besar']...
Sentimen: negatif
--------------------------------------------------------------------------------
Stemming: ['boomer', 'bilang', 'underwear', 'eh', 'underlyingnya', 'bitcoin']...
Sentimen: negatif
--------------------------------------------------------------------------------
Stemming: ['ek', 'aisi', 'wife', 'main', 'bhi', 'deserve', 'karta', 'hu', 'yaar']...
Sentimen: negatif
--------------------------------------------------------------------------------
Stemming: ['bitcoin', 'ziba', 'ntangawuuzi', 'zebalima', 'kumbalama', 'ze', 'nyanja', 'pamela']...
Sentimen: negatif
--------------------------------------------------------------------------------
Stemming: ['bitcoin', 'btc', 'alami', 'turun', 'signifikan', 'februari', 'kisar', 'harga', 'stabil', 'kali']...
Sentimen: positif
--------------------------------------------------------------------------------
Stemming: ['orang', 'cerita', 'depa', 'lupa', 'wallet', 'bitcoin', 'beli', 'btc', 'rega', 'puluh']...
Sentimen: negatif
--------------------------------------------------------------------------------
Stemming: ['bitcoin', 'si', 'relation', 'fear', 'crypto', 'fear', 'greed', 'index', 'titik', 'rendah']...
Sentimen: negatif
--------------------------------------------------------------------------------
Stemming: ['amp', 'trump', 'janji', 'nak', 'rizab', 'bitcoin', 'token', 'trump', 'amp', 'tariff']...
Sentimen: negatif
--------------------------------------------------------------------------------

                                               stemming  score sentiment
0     [chale, man, start, dey, crypto, football, ay,...     -1   negatif
1                         [bitcoin, orange, ogsatoshis]      0   negatif
2     [wahyus, problem, besar, selesai, web, risiko,...     -3   negatif
3     [boomer, bilang, underwear, eh, underlyingnya,...      0   negatif
4     [ek, aisi, wife, main, bhi, deserve, karta, hu...      0   negatif
...                                                 ...    ...       ...
1231  [raja, mata, uang, crypto, bitcoin, postingan,...     -1   negatif
1232  [ktk, kampuni, zenye, market, cap, kubwa, duni...      4   positif
1233  [meinmokhtar, hang, keje, penuh, asb, dah, n, ...      1   positif
1234  [join, gabung, ajar, santuy, bareng, cryptoriz...      2   positif
1235  [selamat, pagi, pagi, cvx, alami, naik, ikut, ...      1   positif

[1236 rows x 3 columns]

In [77]:
#print(df['sentiment'].value_counts())
print(df['sentiment'].duplicated().sum())

1234

In [78]:
df.drop_duplicates(subset=['stemming'], keep='first', inplace=True)
print("\nSebelum dihapus duplikat: ", len(df))
print("Sesudah dihapus duplikat: ")
print(df['sentiment'].duplicated().sum())

Sebelum dihapus duplikat:  1169
Sesudah dihapus duplikat:
1167