In [12]:
import pandas as pd
import ast

In [13]:
df = pd.read_csv('../preprocessing/clean_text.csv')
df

,full_text,case_folding,tokens,normalized,stopword_removal,stemming
0,Chale Your man start dey do Crypto Football ay...,chale your man start dey do crypto football ay...,"['chale', 'your', 'man', 'start', 'dey', 'do',...","['chale', 'your', 'man', 'start', 'dey', 'di',...","['chale', 'man', 'start', 'dey', 'crypto', 'fo...","['chale', 'man', 'start', 'dey', 'crypto', 'fo..."
1,Bitcoin Orange OGsatoshis,bitcoin orange ogsatoshis,"['bitcoin', 'orange', 'ogsatoshis']","['bitcoin', 'orange', 'ogsatoshis']","['bitcoin', 'orange', 'ogsatoshis']","['bitcoin', 'orange', 'ogsatoshis']"
2,WahyuS Problem terbesar yg diselesaikan web ad...,wahyus problem terbesar yg diselesaikan web ad...,"['wahyus', 'problem', 'terbesar', 'yg', 'disel...","['wahyus', 'problem', 'terbesar', 'yang', 'dis...","['wahyus', 'problem', 'terbesar', 'diselesaika...","['wahyus', 'problem', 'besar', 'selesai', 'web..."
3,Buat ngejelasin ke boomer yang bilang Underwea...,buat ngejelasin ke boomer yang bilang underwea...,"['buat', 'ngejelasin', 'ke', 'boomer', 'yang',...","['buat', 'menjelaskan', 'ke', 'boomer', 'yang'...","['boomer', 'bilang', 'underwear', 'eh', 'under...","['boomer', 'bilang', 'underwear', 'eh', 'under..."
4,Ek aisi wife to main bhi deserve karta hu yaar,ek aisi wife to main bhi deserve karta hu yaar,"['ek', 'aisi', 'wife', 'to', 'main', 'bhi', 'd...","['ek', 'aisi', 'wife', 'tapi', 'main', 'bhi', ...","['ek', 'aisi', 'wife', 'main', 'bhi', 'deserve...","['ek', 'aisi', 'wife', 'main', 'bhi', 'deserve..."
...,...,...,...,...,...,...
1231,Siapa yang akan Menjadi Raja Mata Uang Crypto ...,siapa yang akan menjadi raja mata uang crypto ...,"['siapa', 'yang', 'akan', 'menjadi', 'raja', '...","['siapa', 'yang', 'akan', 'menjadi', 'raja', '...","['raja', 'mata', 'uang', 'crypto', 'bitcoin', ...","['raja', 'mata', 'uang', 'crypto', 'bitcoin', ..."
1232,Ktk Kampuni zenye Market Cap kubwa Duniani or ...,ktk kampuni zenye market cap kubwa duniani or ...,"['ktk', 'kampuni', 'zenye', 'market', 'cap', '...","['ktk', 'kampuni', 'zenye', 'market', 'cap', '...","['ktk', 'kampuni', 'zenye', 'market', 'cap', '...","['ktk', 'kampuni', 'zenye', 'market', 'cap', '..."
1233,meinmokhtar Hang keje tak Penuhkan ASB k sbb d...,meinmokhtar hang keje tak penuhkan asb k sbb d...,"['meinmokhtar', 'hang', 'keje', 'tak', 'penuhk...","['meinmokhtar', 'hang', 'keje', 'tak', 'penuhk...","['meinmokhtar', 'hang', 'keje', 'penuhkan', 'a...","['meinmokhtar', 'hang', 'keje', 'penuh', 'asb'..."
1234,Join disini Gabung belajar santuy bareng Crypt...,join disini gabung belajar santuy bareng crypt...,"['join', 'disini', 'gabung', 'belajar', 'santu...","['join', 'disini', 'gabung', 'belajar', 'santu...","['join', 'gabung', 'belajar', 'santuy', 'baren...","['join', 'gabung', 'ajar', 'santuy', 'bareng',..."
1235,Selamat pagi di pagi hari ini CVX mengalami ke...,selamat pagi di pagi hari ini cvx mengalami ke...,"['selamat', 'pagi', 'di', 'pagi', 'hari', 'ini...","['selamat', 'pagi', 'di', 'pagi', 'hari', 'ini...","['selamat', 'pagi', 'pagi', 'cvx', 'mengalami'...","['selamat', 'pagi', 'pagi', 'cvx', 'alami', 'n..."

In [14]:
df.drop(columns=['full_text', 'case_folding', 'tokens', 'normalized', 'stopword_removal'], inplace=True)
df

                                               stemming
0     ['chale', 'man', 'start', 'dey', 'crypto', 'fo...
1                   ['bitcoin', 'orange', 'ogsatoshis']
2     ['wahyus', 'problem', 'besar', 'selesai', 'web...
3     ['boomer', 'bilang', 'underwear', 'eh', 'under...
4     ['ek', 'aisi', 'wife', 'main', 'bhi', 'deserve...
...                                                 ...
1231  ['raja', 'mata', 'uang', 'crypto', 'bitcoin', ...
1232  ['ktk', 'kampuni', 'zenye', 'market', 'cap', '...
1233  ['meinmokhtar', 'hang', 'keje', 'penuh', 'asb'...
1234  ['join', 'gabung', 'ajar', 'santuy', 'bareng',...
1235  ['selamat', 'pagi', 'pagi', 'cvx', 'alami', 'n...

[1236 rows x 1 columns]

In [15]:
df.drop_duplicates(subset=['stemming'], inplace=True)
df

                                               stemming
0     ['chale', 'man', 'start', 'dey', 'crypto', 'fo...
1                   ['bitcoin', 'orange', 'ogsatoshis']
2     ['wahyus', 'problem', 'besar', 'selesai', 'web...
3     ['boomer', 'bilang', 'underwear', 'eh', 'under...
4     ['ek', 'aisi', 'wife', 'main', 'bhi', 'deserve...
...                                                 ...
1231  ['raja', 'mata', 'uang', 'crypto', 'bitcoin', ...
1232  ['ktk', 'kampuni', 'zenye', 'market', 'cap', '...
1233  ['meinmokhtar', 'hang', 'keje', 'penuh', 'asb'...
1234  ['join', 'gabung', 'ajar', 'santuy', 'bareng',...
1235  ['selamat', 'pagi', 'pagi', 'cvx', 'alami', 'n...

[1169 rows x 1 columns]

In [26]:
#Labeling

#set lexicon
pos_inset = pd.read_csv('../../Inset/positive.tsv', sep='\t', header=None, names=['word', 'weight'])
neg_inset = pd.read_csv('../../Inset/negative.tsv', sep='\t', header=None, names=['word', 'weight'])
sentis = pd.read_csv('../../sentistrength_id/sentiwordsid.csv', header=None, names=['word', 'weight'])
sentis = set(sentis['word'].str.lower())


# Pastikan kolom 'stemming' diubah dari string ke list
df['stemming'] = df['stemming'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

# Baca leksikon Inset
# Format tsv: kata\tbobot (atau hanya kata saja)
# Kita akan asumsikan format: kata\tbobot

# Buat kamus leksikon
positive_lexicon = set(pos_inset['word'].str.lower().tolist())
negative_lexicon = set(neg_inset['word'].str.lower().tolist())

print(f"Jumlah kata positif: {len(positive_lexicon)}")
print(f"Jumlah kata negatif: {len(negative_lexicon)}")

def inset_label_sentiment(tokens):
    """
    Label sentimen berdasarkan kemunculan kata dalam leksikon Inset.
    Hanya dua kelas: positif dan negatif.
    Jika tidak ada kata yang cocok, beri label 'netral'.
    """
    if not isinstance(tokens, list):
        return 'netral'
    
    #Hitung pola kemunculan kata
    pos_count = sum(word.lower() in positive_lexicon for word in tokens)
    neg_count = sum(word.lower() in negative_lexicon for word in tokens)
    
    score = pos_count - neg_count
    #Tentukan label berdasarkan bobot
    if score < 0:
        label = 'negatif'
    elif score > 0:
        label = 'positif'
    else:
        # Jika sama atau tidak ada yang cocok, default ke 'negatif'
        # Atau bisa diubah ke 'netral' jika ingin tiga kelas
        label = 'netral'
    
    return score, label

def determine_sentiment(text):
    if not isinstance(text, str):
        return 0, 'netral'
    
    # Hitung skor sentimen dengan bobot
    pos_words = sum(word in sentis for word in text)
    neg_words = sum(word in sentis for word in text)
    
    # Hitung skor sentimen dengan mempertimbangkan jumlah kata
    total_words = pos_words + neg_words
    if total_words == 0:
        sentiment_score = 0
    else:
        sentiment_score = (pos_words - neg_words) / total_words
    
    # Tentukan threshold untuk klasifikasi
    if sentiment_score > 0:  # Threshold positif
        sentiment = 'positif'
    elif sentiment_score < 0:  # Threshold negatif
        sentiment = 'negatif'
    else:  # Zona netral, gunakan pendekatan probabilistik
        sentiment = 'netral'
    
    return sentiment_score, sentiment


# Terapkan pelabelan
df[['inset_score','inset_sentiment']] = df['stemming'].apply(lambda x: pd.Series(inset_label_sentiment(x)))
df[['sentis_score','sentis_sentiment']] = df['stemming'].apply(lambda x: pd.Series(determine_sentiment(x)))

# Tampilkan distribusi
inset_sentiment_dist = df['inset_sentiment'].value_counts()
sentis_sentiment_dist = df['sentis_sentiment'].value_counts()
print("\nDistribusi Sentimen:")
print(inset_sentiment_dist)
print("\nDistribusi Sentimen Sentis:")
print(sentis_sentiment_dist)

# Tampilkan beberapa contoh
print("\nContoh hasil pelabelan inset:")
for i, row in df.head(10).iterrows():
    print(f"Stemming: {row['stemming'][:10]}...")
    print(f"Score: {row['inset_score']}")
    print(f"Sentimen: {row['inset_sentiment']}")
    print("-" * 80)
    
print("\nContoh hasil pelabelan sentis:")
for i, row in df.head(10).iterrows():
    print(f"Stemming: {row['stemming'][:10]}...")
    print(f"Score: {row['sentis_score']}")
    print(f"Sentimen: {row['sentis_sentiment']}")
    print("-" * 80)

#df['sentiment'] = df['stemming'].apply(lambda x: pd.Series(label_sentiment_weighted(x)))
#df[['sentis_score','label_sentis']] = df['stemming'].apply(lambda x: pd.Series(labeling_sentis(x)))

df

Jumlah kata positif: 3608
Jumlah kata negatif: 6607

Distribusi Sentimen:
inset_sentiment
netral     496
positif    376
negatif    297
Name: count, dtype: int64

Distribusi Sentimen Sentis:
sentis_sentiment
netral    1169
Name: count, dtype: int64

Contoh hasil pelabelan inset:
Stemming: ['chale', 'man', 'start', 'dey', 'crypto', 'football', 'ay', 'kak', 'aa', 'bitcoin']...
Score: -1
Sentimen: negatif
--------------------------------------------------------------------------------
Stemming: ['bitcoin', 'orange', 'ogsatoshis']...
Score: 0
Sentimen: netral
--------------------------------------------------------------------------------
Stemming: ['wahyus', 'problem', 'besar', 'selesai', 'web', 'risiko', 'orang', 'orang', 'problem', 'besar']...
Score: -3
Sentimen: negatif
--------------------------------------------------------------------------------
Stemming: ['boomer', 'bilang', 'underwear', 'eh', 'underlyingnya', 'bitcoin']...
Score: 0
Sentimen: netral
--------------------------------------------------------------------------------
Stemming: ['ek', 'aisi', 'wife', 'main', 'bhi', 'deserve', 'karta', 'hu', 'yaar']...
Score: 0
Sentimen: netral
--------------------------------------------------------------------------------
Stemming: ['bitcoin', 'ziba', 'ntangawuuzi', 'zebalima', 'kumbalama', 'ze', 'nyanja', 'pamela']...
Score: 0
Sentimen: netral
--------------------------------------------------------------------------------
Stemming: ['bitcoin', 'btc', 'alami', 'turun', 'signifikan', 'februari', 'kisar', 'harga', 'stabil', 'kali']...
Score: 2
Sentimen: positif
--------------------------------------------------------------------------------
Stemming: ['orang', 'cerita', 'depa', 'lupa', 'wallet', 'bitcoin', 'beli', 'btc', 'rega', 'puluh']...
Score: 0
Sentimen: netral
--------------------------------------------------------------------------------
Stemming: ['bitcoin', 'si', 'relation', 'fear', 'crypto', 'fear', 'greed', 'index', 'titik', 'rendah']...
Score: -2
Sentimen: negatif
--------------------------------------------------------------------------------
Stemming: ['amp', 'trump', 'janji', 'nak', 'rizab', 'bitcoin', 'token', 'trump', 'amp', 'tariff']...
Score: -1
Sentimen: negatif
--------------------------------------------------------------------------------

Contoh hasil pelabelan sentis:
Stemming: ['chale', 'man', 'start', 'dey', 'crypto', 'football', 'ay', 'kak', 'aa', 'bitcoin']...
Score: 0
Sentimen: netral
--------------------------------------------------------------------------------
Stemming: ['bitcoin', 'orange', 'ogsatoshis']...
Score: 0
Sentimen: netral
--------------------------------------------------------------------------------
Stemming: ['wahyus', 'problem', 'besar', 'selesai', 'web', 'risiko', 'orang', 'orang', 'problem', 'besar']...
Score: 0
Sentimen: netral
--------------------------------------------------------------------------------
Stemming: ['boomer', 'bilang', 'underwear', 'eh', 'underlyingnya', 'bitcoin']...
Score: 0
Sentimen: netral
--------------------------------------------------------------------------------
Stemming: ['ek', 'aisi', 'wife', 'main', 'bhi', 'deserve', 'karta', 'hu', 'yaar']...
Score: 0
Sentimen: netral
--------------------------------------------------------------------------------
Stemming: ['bitcoin', 'ziba', 'ntangawuuzi', 'zebalima', 'kumbalama', 'ze', 'nyanja', 'pamela']...
Score: 0
Sentimen: netral
--------------------------------------------------------------------------------
Stemming: ['bitcoin', 'btc', 'alami', 'turun', 'signifikan', 'februari', 'kisar', 'harga', 'stabil', 'kali']...
Score: 0
Sentimen: netral
--------------------------------------------------------------------------------
Stemming: ['orang', 'cerita', 'depa', 'lupa', 'wallet', 'bitcoin', 'beli', 'btc', 'rega', 'puluh']...
Score: 0
Sentimen: netral
--------------------------------------------------------------------------------
Stemming: ['bitcoin', 'si', 'relation', 'fear', 'crypto', 'fear', 'greed', 'index', 'titik', 'rendah']...
Score: 0
Sentimen: netral
--------------------------------------------------------------------------------
Stemming: ['amp', 'trump', 'janji', 'nak', 'rizab', 'bitcoin', 'token', 'trump', 'amp', 'tariff']...
Score: 0
Sentimen: netral
--------------------------------------------------------------------------------

,stemming,inset_score,inset_sentiment,sentis_score,sentis_sentiment
0,"[chale, man, start, dey, crypto, football, ay,...",-1,negatif,0,netral
1,"[bitcoin, orange, ogsatoshis]",0,netral,0,netral
2,"[wahyus, problem, besar, selesai, web, risiko,...",-3,negatif,0,netral
3,"[boomer, bilang, underwear, eh, underlyingnya,...",0,netral,0,netral
4,"[ek, aisi, wife, main, bhi, deserve, karta, hu...",0,netral,0,netral
...,...,...,...,...,...
1231,"[raja, mata, uang, crypto, bitcoin, postingan,...",-1,negatif,0,netral
1232,"[ktk, kampuni, zenye, market, cap, kubwa, duni...",4,positif,0,netral
1233,"[meinmokhtar, hang, keje, penuh, asb, dah, n, ...",1,positif,0,netral
1234,"[join, gabung, ajar, santuy, bareng, cryptoriz...",2,positif,0,netral
1235,"[selamat, pagi, pagi, cvx, alami, naik, ikut, ...",1,positif,0,netral